import Sidebar from "@/components/Sidebar";
import "@/styles/globals.css";
import type { Metadata } from "next";

import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    
    <html lang="en">
      <body className={`${poppins.variable} flex relative`}>
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
